---
- name: Creating docker directory
  file:
    path: /home/{{ remote_user_name }}/docker
    state: directory
    owner: "{{ remote_user_name }}"
    group: "{{ remote_user_name }}"

- name: Copying docker-compose.yml
  template:
    src: "{{ item }}"
    dest: /home/{{ remote_user_name }}/docker/{{ item }}
    owner: "{{ remote_user_name }}"
    group: "{{ remote_user_name }}"
  with_items:
    - docker-compose.yml
    - postgres.init.sh
    - prometheus.yml
    - docker-entrypoint.sh
    - grafana-dashboards.yml
    - grafana-datasources.yml
    - nginx.conf
    - nginx.general.conf
    - nginx.letsencrypt.conf
    - nginx.proxy.conf
    - nginx.security.conf
    - nginx.server.conf
    - nginx.server.ssloff.conf

- name: Checking if Diffie-Hellman keys exist
  stat:
    path: /home/{{ remote_user_name }}/docker/dhparam.pem
  register: dhparam_result

- name: Create the file, if it doesnt exist already
  command: openssl dhparam -out /home/{{ remote_user_name }}/docker/dhparam.pem 2048
  when: not dhparam_result.stat.exists

- name: Creating Let's Encrypt ACME-Challenge directory
  file:
    path: /home/{{ remote_user_name }}/_letsencrypt
    state: directory
    owner: "{{ remote_user_name }}"
    group: "{{ remote_user_name }}"

- name: Copying crawl configuration files
  template:
    src: "nebula.config.json"
    dest: /home/{{ remote_user_name }}/docker/nebula.config.{{ item.name }}.json
    owner: "{{ remote_user_name }}"
    group: "{{ remote_user_name }}"
  with_items: "{{ networks }}"
